-- список месторождений
SELECT 
 PROJ_FINDER, FIELD_NAME, FIELD_CODE 
FROM 
CLASS.ALL_FIELD_HDR FH, SYS.ALL_TABLES AT 
WHERE 
    AT.TABLE_NAME = 'WELL_PERFORATIONS' 
AND AT.OWNER = FH.PROJ_FINDER 
order by field_name


---
SELECT 
 FIELD_NAME,PROJ_FINDER   
FROM 
 CLASS.ALL_FIELD_HDR  
WHERE FIELD_CODE = :b1



SELECT DISTINCT SOURCE, SOURCE FROM DVURECH.V_WELL_PERFORATIONS UNION SELECT '_бХ', null from dual

SELECT 
 WELL_NAME,UWI,ELEVATION 
FROM 
 ( SELECT UWI, WELL_NAME, ELEVATION, LTRIM(SUBSTR( UWI, 1, 4), '0') FIELD_CODE 
   FROM DVURECH.WELL_HDR WH WHERE SUBSTR(UWI,1,5)='01500' ORDER BY UWI) 


-- well_name 1W
SELECT 
 WELL_NAME,UWI,ELEVATION 
FROM 
 ( SELECT UWI, WELL_NAME, ELEVATION, LTRIM(SUBSTR( UWI, 1, 4), '0') FIELD_CODE 
   FROM DVURECH.WELL_HDR WH WHERE SUBSTR(UWI,1,5)='01500' ORDER BY UWI) 





--- главный запрос
SELECT 
SOURCE,      -- источник
COMP_DATE,   -- дата вскрытия
CLOSE_DATE,  -- дата изоляции
PERF_STATUS,
TOP,                 -- верх
BASE,                -- низ
SHORT_PERF_TYPE,     -- тип перфорации
PERF_SHOTS,          -- кол-во отверстий
PERFS_PER,           -- кол-во отверстий на 1м.
REMARKS              -- примечания
FROM 
 DVURECH.V_WELL_PERFORATIONS A 
WHERE 
 source=nvl(:1,source) 
 and (UWI=:2) 
order by comp_date


SELECT 
EVENT_ID,
UWI,
LAYER,
PERF_TYPE,
COMP_TYPE,
POS,
SOURCE,
COMP_DATE,
CLOSE_DATE,
PERF_STATUS,
TOP,
BASE,
SHORT_PERF_TYPE,
PERF_SHOTS,
PERFS_PER,
REMARKS 
FROM DVURECH.V_WELL_PERFORATIONS A 
WHERE 
 source=nvl(null,source) 
 and (UWI='015000001W0') 
order by comp_date



SELECT 
  WELL_NAME,
  UWI,
  ELEVATION 
FROM (SELECT UWI, WELL_NAME, ELEVATION, LTRIM(SUBSTR( UWI, 1, 4), '0') FIELD_CODE 
FROM 
DVURECH.WELL_HDR WH 
 WHERE SUBSTR(UWI,1,5)='01500' AND NOT EXISTS (SELECT 1 FROM DVURECH.V_WELL_PERFORATIONS C WHERE C.UWI = WH.UWI) ORDER BY UWI) 

