
--- после вывода названия
SELECT UWI,WELL_NAME,
DRILLERS_TD, -- забой по стволу
TVD -- забой абсолютный
FROM DVURECH.WELL_HDR 
WHERE UWI LIKE '0150%' AND SUBSTR(UWI,10,2) != 'LE'  
and WELL_NAME='11P'
order by UWI

--  хз зачем нужен этот запрос. выполняется много-мнго раз.
SELECT SHORT_REMARKS   
FROM CODES.WELL_STATUS_CODES  WHERE STATUS = 'UNKNOWN'

-- инфа о колонне
SELECT 
 UWI,
 TUBING_TYPE, --  тип колонны. 2-кондуктор , 3-эксплутационный
 TUBING_DEPTH,-- глубина колонны в м.
 DIAMETER, -- диаметр колонны в м.
 SHOE_DEPTH, -- глубина башмака
 TUBING_DATE, -- дата установки колонны
 LANTERNS,    -- кол-во фонарей
 RING_DEPTH,  -- глубина кольца
 VALVE_DEPTH, -- глубина клапана
 CEMENT_HEIGHT, -- высота цемента
 DOCUMENT_ID,  -- документ
 REMARKS,      -- примечание
 LAST_UPDATE   -- дата последнего изменения
FROM 
DVURECH.TUBULARS WHERE (UWI='015000011P0')
&P1_SCHEMA..
:P1_UWI
f?p=&APP_ID.:2:&SESSION.::&DEBUG.::P2_UWI,P2_TUBING_TYPE,P2_TUBING_DEPTH,P2_DIAMETER,P2_SHOE_DEPTH,P2_TUBING_DATE,P2_LANTERNS,P2_RING_DEPTH,P2_VALVE_DEPTH,P2_CEMENT_HEIGHT,P2_DOCUMENT_ID,P2_REMARKS:#UWI#,#TUBING_TYPE#,#TUBING_DEPTH#,#DIAMETER#,#SHOE_DEPTH#,#TUBING_DATE#,#LANTERNS#,#RING_DEPTH#,#VALVE_DEPTH#,#CEMENT_HEIGHT#,#DOCUMENT_ID#,#REMARKS#


-- инфа о трубе
SELECT 
 UWI,
 TUBING_TYPE, -- тип колонны. 2-кондуктор , 3-эксплутационный
 SECTION,     -- номер секции
 TOP,         -- верх (м)
 BASE,        -- низ (м)
 STEEL_SPEC,  -- спецификация стали
 PIPE_THICKNESS, -- толщина стенок
 REMARKS 
FROM DVURECH.TUBULAR_SECTIONS 
WHERE (UWI='015000011P0') 
and (TUBING_TYPE=2) 
order by SECTION

f?p=&APP_ID.:2:&SESSION.::&DEBUG.::P2_UWI,P2_TUBING_TYPE,P2_SECTION,P2_TOP,P2_BASE,P2_STEEL_SPEC,P2_PIPE_THICKNESS,P2_TS_REMARKS:#COL01#,#COL02#,#COL03#,#COL04#,#COL05#,#COL06#,#COL07#,#COL08#


-- цемент
SELECT 
TUBING_TYPE, --  тип колонны. 2-кондуктор , 3-эксплутационный
UWI,
CEMENT_NUM,  -- номер цемента
CEMENT_TYPE, -- тип цемента
CEMENT_AMOUNT	 -- кол-во цемента
CEMENT_DENSITY, -- плотность цемента
CEMENT_UNIT     -- единица измерения
FROM 
 DVURECH.TUBULAR_CEMENT 
WHERE 
    (TUBING_TYPE=2) 
and (UWI='015000011P0') 
order by CEMENT_NUM
f?p=&APP_ID.:2:&SESSION.::&DEBUG.::P2_TUBING_TYPE,P2_UWI,P2_CEMENT_NUM,P2_CEMENT_TYPE,P2_CEMENT_AMOUNT,P2_CEMENT_DENSITY,P2_CEMENT_UNIT:#COL01#,#COL02#,#COL03#,#COL04#,#COL05#,#COL06#,#COL07#



SELECT 
 UWI,
 TUBING_TYPE, --  тип колонны. 2-кондуктор , 3-эксплутационный
 SECTION,     -- номер секции
 TOP,         -- верх (м)
 BASE,        -- низ (м)
 STEEL_SPEC,  -- спецификация стали
 PIPE_THICKNESS, -- толщина стенок
 REMARKS 
FROM &P1_SCHEMA..TUBULAR_SECTIONS@FINDER_V890_LNK 
WHERE 
    UWI=:P1_UWI
AND TUBING_TYPE IN ( 
   SELECT TYPE FROM class.tubing_desc@finder_v890_lnk
   WHERE name_rus=:P1_TUBING_TYPE )
ORDER BY SECTION



<img src="#WORKSPACE_IMAGES#edit16.gif">


UPDATE_TUBE('VAX','03450010700','КОНДУКТОР','111','','','','','','','','','');
UPDATE_TUBE('VAX','03450010700','2','111','','','','','','','','','');

UPDATE VAX.TUBULARS@FINDER_V890_LNK SET tubing_type=1, TUBING_DEPTH=3
    WHERE uwi='034500010P0' AND tubing_type=1; 


?p=&APP_ID.:2:&SESSION.::&DEBUG.::
P1_UWI,
P1_TUBING_TYPE,
P1_TUBING_DEPTH,
P1_DIAMETER,
P1_SHOE_DEPTH,
P1_TUBING_DATE,
P1_LANTERNS,
P1_RING_DEPTH,
P1_VALVE_DEPTH,
P1_CEMENT_HEIGHT,
P1_DOCUMENT_ID,
P1_REMARKS:
#COL01#,#COL02#,#COL03#,#COL04#,#COL05#,#COL06#,#COL07#,#COL08#,#COL09#,#COL10#,#COL11#,#COL12#,#COL13#




?p=&APP_ID.:2:&SESSION.::&DEBUG.::
P2_UWI,
P2_TUBING_TYPE,
P2_TUBING_DEPTH,
P2_DIAMETER,
P2_SHOE_DEPTH,
P2_TUBING_DATE,
P2_LANTERNS,
P2_RING_DEPTH,
P2_VALVE_DEPTH,
P2_CEMENT_HEIGHT,
P2_DOCUMENT_ID,
P2_REMARKS:
#COL01#,#COL02#,#COL03#,#COL04#,#COL05#,#COL06#,#COL07#,#COL08#,#COL09#,#COL10#,#COL11#,#COL12#






f?p=&APP_ID.:2:&SESSION.::&DEBUG.::P2_UWI,P2_TUBING_TYPE,P2_TUBING_DEPTH,P2_DIAMETER,P2_SHOE_DEPTH,P2_TUBING_DATE,P2_LANTERNS,
P2_RING_DEPTH,P2_VALVE_DEPTH,P2_CEMENT_HEIGHT,P2_DOCUMENT_ID,P2_REMARKS,P2_HIDDEN_COL1,P2_HIDDEN_COL2,P2_HIDDEN_CEM,P2_HIDDEN_TUB
:#COL01#,#COL02#,#COL03#,#COL04#,#COL05#,#COL06#,#COL07#,#COL08#,#COL09#,#COL10#,#COL11#,#COL12#,1,1,0,0



f?p=&APP_ID.:2:&SESSION.::&DEBUG.::P2_UWI,P2_TUBING_TYPE,P2_SECTION,P2_TOP,P2_BASE,P2_STEEL_SPEC,P2_PIPE_THICKNESS,P2_TS_REMARKS,P2_HIDDEN_COL1,P2_HIDDEN_COL2,P2_HIDDEN_CEM,P2_HIDDEN_TUB:#COL01#,#COL02#,#COL03#,#COL04#,#COL05#,#COL06#,#COL07#,#COL08#,0,0,0,1
f?p=&APP_ID.:2:&SESSION.::&DEBUG.::P2_TUBING_TYPE,P2_UWI,P2_CEMENT_NUM,P2_CEMENT_TYPE,P2_CEMENT_AMOUNT,P2_CEMENT_DENSITY,P2_CEMENT_UNIT,P2_HIDDEN_COL1,P2_HIDDEN_COL2,P2_HIDDEN_TUB,P2_HIDDEN_TUB:#COL01#,#COL02#,#COL03#,#COL04#,#COL05#,#COL06#,#COL07#,0,0,1,0
f?p=&APP_ID.:2:&SESSION.::&DEBUG.::P2_UWI,P2_TUBING_TYPE,P2_TUBING_DEPTH,P2_DIAMETER,P2_SHOE_DEPTH,P2_TUBING_DATE,P2_LANTERNS,P2_RING_DEPTH,P2_VALVE_DEPTH,P2_CEMENT_HEIGHT,P2_DOCUMENT_ID,P2_REMARKS,P2_HIDDEN_COL1,P2_HIDDEN_COL2,P2_HIDDEN_CEM,P2_HIDDEN_TUB:#COL01#,#COL02#,#COL03#,#COL04#,#COL05#,#COL06#,#COL07#,#COL08#,#COL09#,#COL10#,#COL11#,#COL12#,1,1,0,0



f?p=&APP_ID.:2:&SESSION.::&DEBUG.::P2_UWI_TUB,P2_TUBING_TYPE_TUB,P2_SECTION:#COL01#,#COL02#,#COL03#


f?p=&APP_ID.:2:&SESSION.::&DEBUG.::P2_TUBING_TYPE,P2_UWI,P2_CEMENT_NUM:#COL01#,#COL02#,#COL03#


f?p=&APP_ID.:2:&SESSION.::&DEBUG.::P2_UWI,P2_TUBING_TYPE,P2_TUBING_DEPTH,P2_DIAMETER,P2_SHOE_DEPTH,P2_TUBING_DATE,P2_LANTERNS,P2_RING_DEPTH,P2_VALVE_DEPTH,P2_CEMENT_HEIGHT,P2_DOCUMENT_ID,P2_REMARKS,P2_HIDDEN_COL1,P2_HIDDEN_COL2,P2_HIDDEN_CEM,P2_HIDDEN_TUB,P1_IS_INSERT:#COL01#,#COL02#,#COL03#,#COL04#,#COL05#,#COL06#,#COL07#,#COL08#,#COL09#,#COL10#,#COL11#,#COL12#,1,0,0,0,0


SELECT 
  A.FIELD_NAME AS FN , A.FIELD_CODE AS FC, A.PROJ_FINDER AS PF
FROM 
  CLASS.ALL_FIELD_HDR@finder_v890_lnk A,
  SYS.ALL_CATALOG@finder_v890_lnk C 
WHERE 
    A.PROJ_FINDER = C.OWNER 
AND C.TABLE_NAME = 'WELL_HDR'  
AND FIELD_NAME > 'A' 
ORDER BY 1




P1_SCHEMA #PROJ_FINDER#
P1_PROJECT_NAME #FIELD_NAME#
P1_FIELD_CODE #FIELD_CODE# 



P1_FIELD_CODE #FIELD_CODE#

P1_SCHEMA #PROJ_FINDER#